//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Electronics_Shop.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_order()
        {
            this.Tbl_ShippingDetails = new HashSet<Tbl_ShippingDetails>();
            this.Tbl_OrderStatus = new HashSet<Tbl_OrderStatus>();
            this.tbl_delivery = new HashSet<tbl_delivery>();
        }
    
        public int o_id { get; set; }
        public Nullable<int> o_fk_pro { get; set; }
        public Nullable<int> o_fk_invoice { get; set; }
        public Nullable<System.DateTime> o_date { get; set; }
        public Nullable<int> o_qty { get; set; }
        public Nullable<double> o_bill { get; set; }
        public Nullable<double> o_unitprice { get; set; }
    
        public virtual tbl_invoice tbl_invoice { get; set; }
        public virtual Tbl_Product Tbl_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ShippingDetails> Tbl_ShippingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_OrderStatus> Tbl_OrderStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_delivery> tbl_delivery { get; set; }
    }
}
