//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Electronics_Shop.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_OrderStatus
    {
        public int OrderStatusId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string OrderStatus { get; set; }
    
        public virtual tbl_order tbl_order { get; set; }
    }
}
